### ISSUE TITLE
How to find GAM-Net2

### ISSUE THREAD

**Issue by YeongHyeon** [luow23/AMI-Net#1]
Hi, 

I am trying to train some model by 'uniad_train_mvtec.py'.
However, it crashed with error ```FileNotFoundError: [Errno 2] No such file or directory: 'E:\\GAM-Net2\\data\\mvtec_anomaly_detection/bottle/test'```

It appears to be related to line 28 of 'datasets/mvtec.py'.
anomaly_sourec_path=r'E:\GAM-Net2\data\nature'
(https://github.com/luow23/AMI-Net/blob/53c41a27a2b345a4acd63b6315c91dfb1e9c86a7/datasets/mvtec.py#L28)

How can I found the location of GAM-Net2 or prepare them to utilize training script 'uniad_train_mvtec.py'.?

Thank you for your kind response.

**Comment by luow23** [comment]
Thank you for your attention. You just need to change the data path in uniad_config.py.
